-- 부서(DEPT) 테이블 생성
CREATE TABLE DEPT (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

-- 사원(EMP) 테이블 생성
CREATE TABLE EMP (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

-- 부서(DEPT) 데이터 삽입
INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

-- 사원(EMP) 데이터 삽입
INSERT INTO EMP VALUES (7369, 'SMITH', 'CLERK', 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 30);
INSERT INTO EMP VALUES (7521, 'WARD', 'SALESMAN', 30);
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER', 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', 30);
INSERT INTO EMP VALUES (7698, 'BLAKE', 'MANAGER', 30);
INSERT INTO EMP VALUES (7782, 'CLARK', 'MANAGER', 10);
INSERT INTO EMP VALUES (7788, 'SCOTT', 'ANALYST', 20);
INSERT INTO EMP VALUES (7839, 'KING', 'PRESIDENT', 10);
INSERT INTO EMP VALUES (7844, 'TURNER', 'SALESMAN', 30);
INSERT INTO EMP VALUES (7876, 'ADAMS', 'CLERK', 20);
INSERT INTO EMP VALUES (7900, 'JAMES', 'CLERK', 30);
INSERT INTO EMP VALUES (7902, 'FORD', 'ANALYST', 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK', 10);

-- 테이블 확인
SELECT * FROM DEPT;
SELECT * FROM EMP;